### ISSUE TITLE
print syntax objects natively in the DrRacket REPL

### ISSUE THREAD

**Issue by mbutterick** [AlexKnauth/debug#16]
Of course, DrRacket doesn’t need syntax objects reduced to strings, becuase it can produce the nice clickable native display. It’s not hard to patch `report` to do this, except for one thing: restricting the behavior to the DrRacket REPL (as opposed to any REPL). 

So I think this reduces to the question: Is there a way for a macro to detect whether it’s being invoked within DrRacket?

**Comment by mbutterick** [comment]
I had an idea that one could piggyback on one of the DrRacket-specific keys in the `get-info` function, like `drracket:toolbar-buttons`, or `drracket:indentation`, but a) this is a little too hacky even for me and b) are these called while loading a metalanguage? I think not — just the `get-info` for the host language.

**Comment by AlexKnauth** [comment]
I'm not sure what you mean. Are you talking about this?
<img width="315" alt="debug-syntax" src="https://user-images.githubusercontent.com/6600123/36950102-18f403b8-1fbf-11e8-8917-d57c9f43b4e1.png">

Or do you mean something else?

**Comment by AlexKnauth** [comment]
After your pull request opened the door for more helper functions, I changed it to use a `pretty-eprintf` function and a "fake" `values` struct instead of stringify-results. With that `pretty-eprintf` function, it looks like the example from the comment above.

**Comment by mbutterick** [comment]
Sorry, my error. My last update didn’t get #15 so I didn’t notice this had been improved. Another wish granted! Thanks.

**Comment by mbutterick** [comment]
Actually, maybe this is what confused me — though `debug/report` will print the whole syntax object in phase 0, in phase 1 it apparently still reduces it to a string (and of course, phase 1 is where one is likely to be debugging syntax objects):

```racket
#lang racket
(require (for-syntax debug/report)) 
(begin-for-syntax  (report #'foo))

(require debug/report)
(report #'foo)
```
<img width="434" alt="screen shot 2018-03-04 at 1 42 08 pm" src="https://user-images.githubusercontent.com/1425051/36950928-dfc7098a-1fb1-11e8-804e-02467dde03e5.png">

**Comment by AlexKnauth** [comment]
Huh. It works when I use `eprintf`, but not when I use `pretty-eprintf`. I don't know what's going on other than that.
