### ISSUE TITLE
build error caused by package conflict

### ISSUE THREAD

**Issue by mbutterick** [AlexKnauth/debug#17]
There’s [a build error](https://travis-ci.org/AlexKnauth/debug/jobs/345752607) on `debug` that’s percolating through to my Travis builds that rely on `debug` (naturally):

```text
 raco pkg install: packages conflict
  package: rackunit-typed
  package: typed-racket-more
  module path: typed/rackunit/type-env-ext
```

**Comment by AlexKnauth** [comment]
This could probably be solved by changing the package entry for `rackunit-typed` to add a version exception. For racket versions before `rackunit-typed` existed, it should point to an "empty package."

**Comment by AlexKnauth** [comment]
I've made a pull request to try to fix this on `rackunit-typed`:
https://github.com/racket/rackunit/pull/93

**Comment by AlexKnauth** [comment]
@mbutterick Now with that PR to `rackunit-typed` merged, that build error should be fixed.
