### ISSUE TITLE
Use with typed/racket

### ISSUE THREAD

**Issue by winny-** [AlexKnauth/debug#18]
Is it possible to use the reader extension with typed racket?

**Comment by AlexKnauth** [comment]
Yes. But for reasons that I don't really know how to fix, you need to have both `#lang debug ....` and `(require typed/debug/report)` in your program. 
```racket
#lang debug typed/racket
(require typed/debug/report)  ; without this it fails

(define x 2)
(define (f) #R x)
```

Also, Typed Racket's type inference can only handle `#R`, `#RR`, and `#RRR` in expression positions, not possible definition positions. If you put `#R x` in the top level of a module, TR will fail, but if you put it in the body of a function or something it should work.

**Comment by AlexKnauth** [comment]
After commit https://github.com/AlexKnauth/debug/commit/26de1c495059201c27e665d037dad4abbc871b38, the problem with TR's inference on `#R` in possible-definition positions should be fixed.

**Comment by winny-** [comment]
Thank you for the prompt clarification :). I had missed the necessary require.
