### ISSUE TITLE
Allow pretty-printing

### ISSUE THREAD

**Issue by stamourv** [AlexKnauth/debug#2]
First, this package is awesome!
When using it to debug TR, I sometimes need to print large values. Pretty-printing would make them more readable.

**Comment by AlexKnauth** [comment]
Is there a way to pretty-print values with indentation to start with? 

If there's not I guess I could pretty print it as an s-expression that includes both the expression and the value. Which would be better?

**Comment by stamourv** [comment]
The latter is fine. Or you could print to a string, then strip the outer layer of parens.

**Comment by AlexKnauth** [comment]
I just tried this, not expecting it to work, but it did!

``` racket
#lang racket
(require racket/pretty)
(struct thing (name val)
  #:methods gen:custom-write
  [(define (write-proc this out mode)
     (fprintf out "~a = ~v" (thing-name this) (thing-val this)))])
(parameterize ([pretty-print-columns 56])
  (pretty-print (thing 'x '(define (f n) (for/list ([i (in-range n)] #:when (odd? i)) (* 2 i))))))
```

However, I want this to, one, not have any typed racket dependencies, so that people can use it to debug typed racket, but also to be able to be used in typed code. I don't think using a struct like this would allow both of those options. Is there a better way to get around this?

**Comment by AlexKnauth** [comment]
Ok, you can now use the pretty branch to do that: https://github.com/AlexKnauth/debug/tree/pretty

**Comment by stamourv** [comment]
Thanks! I'll give it a try.
To avoid the dependency, would it work to have both `debug` and `typed/debug`? I think they could even be provided by the same package. The overall package would depend on TR, but the `debug` collection would not, so it could still be used inside TR.
