### ISSUE TITLE
Add MIT License

### ISSUE THREAD

**Issue by AlexKnauth** [AlexKnauth/debug#22]
Contributors @SuzanneSoy, @mbutterick, @sorawee, and @florence, I would like to add the MIT License to this repository.

If you agree, please post a message saying so, e.g. — "I hereby license my contributions to `debug` under the MIT license."

**Comment by sorawee** [comment]
I hereby license my contributions to `debug` under the MIT license.

**Comment by mbutterick** [comment]
I hereby license my contributions to `debug` under the MIT license.

**Comment by SuzanneSoy** [comment]
I hereby license my contributions to debug under the MIT license.

**Comment by SuzanneSoy** [comment]
Also, should you ever want to change the license again, feel free to do so.

I hereby release my contributions to debug in the public domain via the CC0 Creative Commons Public Domain Dedication. The intent is that the license of this software can be freely changed in the future without having to seek further approval from me, including choosing to release the software in the Public Domain, under the Unlicense, CC0, WTFPL, MIT, any BSD license, any GPL license, or any other open-source or proprietary license.
