### ISSUE TITLE
Nested debug forms are difficult to read

### ISSUE THREAD

**Issue by jackfirth** [AlexKnauth/debug#4]
The following:

``` racket
#R(+ 1 #R(+ 2 3))
```

Produces this debug output:

```
(+ 2 3) = 5
(+ 1 (let () (local-require (only-in debug/report (report report))) (report (+ 2 3)))) = 6
```

The outer #R captures the macro expansion of the inner #R. This is difficult to read, especially with more complex expressions. Changing this is probably more trouble than it's worth, but it's an interesting problem at least.

**Comment by AlexKnauth** [comment]
It might be possible to use syntax-properties or something to avoid that; I'll try this afternoon.

**Comment by AlexKnauth** [comment]
Ok. I finally fixed this - sorry it took so long. Now it does this:

``` racket
(+ 2 3) = 5
(+ 1 (report (+ 2 3))) = 6
```

Which still isn't ideal, but it's a lot better than it was.
