### ISSUE TITLE
`(debug-repl)` will fail if immutable top-level variable is shadowed by a local variable

### ISSUE THREAD

**Issue by florence** [AlexKnauth/debug#7]
In:

```
#lang racket
(require debug/repl)
(define x 10)
(define (f x)
  (+ x (debug-repl)))
```

Running `(f 10)` results in:

```
namespace-set-variable-value!: assignment disallowed;
 cannot re-define a constant
  constant: x
```

**Comment by AlexKnauth** [comment]
This is an interesting failure. Do you have any idea if I can create a namespace with a shadowed version?

**Comment by florence** [comment]
I don't know of one. I tried to make one so that `resume` function I'm implementing https://github.com/florence/debug/commit/b6c2266dbe0a46f74f8c1cd17b425ae0ca10a215 could property reset the namespace, and couldn't figure out a way to do it with namespaces.

Maybe the REPL could use a custom `#%top` that looks in some hash table that has the information about local variable (basically `vect` from https://github.com/AlexKnauth/debug/blob/master/debug/repl.rkt#L36 ). This feels really ugly, but then again this _is_ scary reflection land. This would have the side effect of fixing #5.

**Comment by AlexKnauth** [comment]
Oh! Ok, I'll try that this afternoon.

**Comment by AlexKnauth** [comment]
Wait, how do I add a `#%top` macro to a namespace? There's no `namespace-set-syntax-transformer-value!` as far as I know, and I don't want to rely on `define-syntax` being bound to the correct thing in the namespace.

**Comment by florence** [comment]
I would have a separate module that's something like:

```
#lang racket/base
(provide (rename-out [in:top #%top]))
... an implementation ...
```

then use `dynamic-require` to get it into the current namespace. 

This still isn't great because it can't fall back to the modules `#%top`. Not sure of a good way around that...

**Comment by AlexKnauth** [comment]
Fixed by https://github.com/AlexKnauth/debug/commit/11ce8f0b32a5c767e3ecc18950aeae2e4e65b7d4
