### ISSUE TITLE
`(debug-repl)` causes a use-before-defined error

### ISSUE THREAD

**Issue by florence** [AlexKnauth/debug#9]
```
#lang racket
(require debug/repl)

(define (test)
  (when #t
    (debug-repl))
  (define a 1)
  a)
(test)
```

Causes the error: `a: undefined; cannot use before initialization`

**Comment by AlexKnauth** [comment]
I could fix this if I could define `a` as a macro in the namespace that expanded to a zero-argument function call of a function that references the outside `a`. 

I'm still not sure how to do that though.
